controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\BaseController::index

api_doc:
 path: /doc
 controller: api_platform.swagger_ui.action
